addr=":8306"
enables="mysql,mongo,redis"

[mysql]
instances="rw@@127.0.0.1:3306,ro@@192.168.x.x:3307"
user="dbrt"
password="dbrt"
db="dbrt"
threads=4

[mongo]
instances="127.0.0.1:27017,192.168.x.x:27018"
user="dbrt"
password="dbrt"
db="dbrt"
threads=4

[redis]
instances="password@@127.0.0.1:6379,password@@192.168.x.x:6380"
threads=8
