{
 "title": "DB Response Time",
 "description": "Response Time",
 "tags": [ "Response Time" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL Response Time Select (us)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dbrt_mysql_response_time_select_us",
     "legendFormat": "{{instence_type}}@{{targetinstance}}"
    }
   ]
  },
  {
   "title": "MySQL Response Time Connect (us)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dbrt_mysql_response_time_connect_us",
     "legendFormat": "{{instence_type}}@{{targetinstance}}"
    }
   ]
  },
  {
   "title": "MySQL Response Time Insert (us)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dbrt_mysql_response_time_insert_us",
     "legendFormat": "{{instence_type}}@{{targetinstance}}"
    }
   ]
  },
  {
   "title": "MySQL Response Time Update (us)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dbrt_mysql_response_time_update_us",
     "legendFormat": "{{instence_type}}@{{targetinstance}}"
    }
   ]
  },
  {
   "title": "MySQL Response Time Delete (us)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dbrt_mysql_response_time_delete_us",
     "legendFormat": "{{instence_type}}@{{targetinstance}}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Response Time Get (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_redis_response_time_get_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    },
    {
     "title": "Redis Response Time Connect (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_redis_response_time_connect_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    },
    {
     "title": "Redis Response Time Set (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_redis_response_time_set_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB Response Time Find (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_mongo_response_time_find_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    },
    {
     "title": "MongoDB Response Time Connect (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_mongo_response_time_connect_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    },
    {
     "title": "MongoDB Response Time Insert (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_mongo_response_time_insert_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    },
    {
     "title": "MongoDB Response Time Update (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_mongo_response_time_update_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    },
    {
     "title": "MongoDB Response Time Delete (us)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dbrt_mongo_response_time_delete_us",
       "legendFormat": "{{targetinstance}}"
      }
     ]
    }
   ]
  }
 ]
}